import { NextRequest, NextResponse } from "next/server";
import { cookies } from "next/headers";
import { z } from "zod";
import { verifyToken } from "@/lib/auth";
import { db } from "@/lib/db";
const schema=z.object({items:z.array(z.object({productId:z.string(),categoryId:z.string(),productName:z.string(),quantity:z.number().int().positive(),unitPrice:z.number().nonnegative(),selectedSize:z.string().optional(),addons:z.array(z.object({name:z.string(),price:z.number().nonnegative()})).default([])})).min(1),discountAmount:z.number().nonnegative().default(0)});
export async function GET(request:NextRequest){const user=await verifyToken((await cookies()).get("erp_session")?.value);if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const query=request.nextUrl.searchParams;const invoices=await db.invoice.findMany({where:{cashierId:user.role==="CASHIER"?user.userId:(query.get("cashierId")||undefined),branchId:query.get("branchId")||undefined,createdAt:query.get("from")?{gte:new Date(query.get("from")!)}:undefined},include:{cashier:{select:{id:true,name:true}},branch:true,items:{include:{addons:true}},payment:true},orderBy:{createdAt:"desc"},take:100});return NextResponse.json(invoices)}
export async function POST(request:Request){const user=await verifyToken((await cookies()).get("erp_session")?.value);if(user?.role!=="CASHIER")return NextResponse.json({error:"Forbidden"},{status:403});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid order",details:parsed.error.flatten()},{status:400});const subtotal=parsed.data.items.reduce((a,x)=>a+x.unitPrice*x.quantity,0);const total=Math.max(0,subtotal-parsed.data.discountAmount);const invoice=await db.invoice.create({data:{number:`INV-${Date.now().toString().slice(-8)}`,subtotal,discountAmount:parsed.data.discountAmount,totalAmount:total,cashierId:user.userId,branchId:user.branchId,items:{create:parsed.data.items.map(x=>({productId:x.productId,categoryId:x.categoryId,productNameSnapshot:x.productName,quantity:x.quantity,unitPrice:x.unitPrice,selectedSizeSnapshot:x.selectedSize,totalPrice:x.unitPrice*x.quantity,addons:{create:x.addons.map(a=>({nameSnapshot:a.name,priceSnapshot:a.price}))}}))},payment:{create:{amount:total}}},include:{items:{include:{addons:true}},payment:true}});return NextResponse.json(invoice,{status:201})}

