"use client";
import Link from "next/link";
import { ArrowUpRight, Boxes, CirclePercent, CreditCard, FileText, Plus, ReceiptText, ShoppingBag, TrendingUp, UserPlus } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { useLanguage } from "@/components/language-provider";
import { invoices, products, salesDays } from "@/lib/demo-data";

export default function Dashboard(){const {t,locale}=useLanguage(); const currency=locale==="ar"?"₪":"₪"; const stats=[
  {label:t("todayIncome"),value:`${currency} 1,284.50`,delta:"+12.4%",icon:CreditCard,color:"bg-primary-soft text-primary"},
  {label:t("weekIncome"),value:`${currency} 8,642.25`,delta:"+8.1%",icon:TrendingUp,color:"bg-success/10 text-success"},
  {label:t("monthIncome"),value:`${currency} 31,906.00`,delta:"+15.7%",icon:ShoppingBag,color:"bg-warning/10 text-warning"},
  {label:t("totalInvoices"),value:"1,048",delta:"+92",icon:ReceiptText,color:"bg-secondary/10 text-secondary"},
];return <AppShell title={t("dashboard")} description="Monday, July 6 · Main Branch" action={<Link href="/admin/products" className="btn-primary hidden sm:flex items-center gap-2"><Plus size={17}/>{t("addProduct")}</Link>}>
  <section className="grid grid-cols-2 xl:grid-cols-4 gap-3 sm:gap-5">{stats.map(({label,value,delta,icon:Icon,color})=><div key={label} className="card p-4 sm:p-5"><div className="flex justify-between items-start"><div className={`size-10 sm:size-11 rounded-xl grid place-items-center ${color}`}><Icon size={21}/></div><span className="text-success text-xs font-bold flex gap-1 items-center"><ArrowUpRight size={13}/>{delta}</span></div><p className="text-muted text-xs sm:text-sm mt-5">{label}</p><p className="text-xl sm:text-2xl font-bold mt-1 tracking-tight">{value}</p></div>)}</section>
  <section className="grid xl:grid-cols-[1.65fr_1fr] gap-5 mt-5"><div className="card p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">{t("salesOverview")}</h2><p className="text-muted text-xs mt-1">Last 14 days · gross revenue</p></div><select className="input !w-auto !h-10 text-sm"><option>Last 14 days</option></select></div><div className="mt-8 h-56 flex items-end gap-2 border-b border-border relative"><span className="absolute top-0 start-0 text-xs text-muted">₪ 1.5k</span><span className="absolute top-1/2 start-0 text-xs text-muted">750</span>{salesDays.map((v,i)=><div key={i} title={`${v*10} ₪`} className="flex-1 bg-primary-soft hover:bg-primary rounded-t-md transition-all" style={{height:`${v/1.55}%`}}/> )}</div><div className="flex justify-between text-[10px] text-muted mt-2"><span>Jun 23</span><span>Jun 27</span><span>Jul 1</span><span>Jul 6</span></div></div>
    <div className="card p-5"><div className="flex justify-between"><h2 className="font-bold">{t("topProducts")}</h2><Link href="/admin/reports" className="text-primary text-sm font-bold">{t("viewAll")}</Link></div><div className="mt-5 space-y-4">{products.slice(0,5).map((p,i)=><div key={p.id} className="flex items-center gap-3"><span className="text-muted text-xs w-3">{i+1}</span><div className={`size-10 rounded-xl product-${p.color} grid place-items-center text-xl bg-background`}>{p.emoji}</div><div className="min-w-0 flex-1"><p className="font-semibold text-sm truncate">{locale==="ar"?p.nameAr:p.nameEn}</p><p className="text-xs text-muted">{84-i*9} sold</p></div><b className="text-sm">₪ {(714-i*76).toFixed(0)}</b></div>)}</div></div></section>
  <section className="grid xl:grid-cols-[1.65fr_1fr] gap-5 mt-5"><div className="card overflow-hidden"><div className="p-5 flex justify-between"><h2 className="font-bold">{t("recentInvoices")}</h2><Link href="/admin/invoices" className="text-primary text-sm font-bold">{t("viewAll")}</Link></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-background text-muted text-xs"><tr><th className="p-3 text-start">{t("invoice")}</th><th className="p-3 text-start">{t("employee")}</th><th className="p-3 text-start">{t("items")}</th><th className="p-3 text-end">{t("total")}</th></tr></thead><tbody>{invoices.slice(0,4).map(inv=><tr key={inv.number} className="border-t border-border"><td className="p-3"><Link href={`/invoice/${inv.number}`} className="font-bold text-primary">#{inv.number}</Link><small className="block text-muted">{inv.time}</small></td><td className="p-3">{inv.cashier}</td><td className="p-3">{inv.items}</td><td className="p-3 text-end font-bold">₪ {inv.total.toFixed(2)}</td></tr>)}</tbody></table></div></div>
    <div className="card p-5"><h2 className="font-bold">{t("quickAction")}</h2><div className="grid grid-cols-3 gap-3 mt-5">{[[Boxes,"manageCatalog","/admin/products"],[CirclePercent,"createOffer","/admin/discounts"],[UserPlus,"inviteCashier","/admin/employees"]].map(([Icon,label,href])=>{const I=Icon as typeof Boxes;return <Link key={label as string} href={href as string} className="bg-background rounded-xl p-3 text-center hover:bg-primary-soft transition"><I className="mx-auto text-primary" size={22}/><span className="text-xs font-semibold block mt-2">{t(label as "manageCatalog")}</span></Link>})}</div><div className="mt-5 bg-secondary text-white rounded-xl p-4 flex items-center gap-3"><div className="size-10 rounded-lg bg-white/10 grid place-items-center"><FileText/></div><div><p className="font-semibold text-sm">Daily close</p><p className="text-sidebar-muted text-xs">Ready at 11:00 PM</p></div></div></div></section>
  </AppShell>}

