"use client";
import Link from "next/link";
import { Download, Eye } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageToolbar, Pagination, StatusBadge } from "@/components/ui";
import { useLanguage } from "@/components/language-provider";
import { invoices } from "@/lib/demo-data";
export default function InvoicesPage(){const {t}=useLanguage();return <AppShell title={t("invoices")} description="All completed sales and receipts" action={<button className="btn-secondary flex items-center gap-2"><Download size={17}/><span className="hidden sm:inline">{t("export")}</span></button>}><PageToolbar><select className="input !w-auto"><option>{t("allBranches")}</option></select><select className="input !w-auto"><option>{t("employee")}: All</option></select></PageToolbar><div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-sm"><thead className="bg-background text-muted"><tr><th className="p-4 text-start">{t("invoice")}</th><th className="p-4 text-start">{t("date")}</th><th className="p-4 text-start">{t("employee")}</th><th className="p-4 text-start">{t("branch")}</th><th className="p-4 text-start">{t("items")}</th><th className="p-4 text-start">{t("status")}</th><th className="p-4 text-end">{t("total")}</th><th/></tr></thead><tbody>{[...invoices,...invoices.slice(1,4).map((x,i)=>({...x,number:`INV-104${3-i}`,date:"Jul 5, 2026"}))].map(inv=><tr key={inv.number} className="border-t border-border hover:bg-background"><td className="p-4 font-bold text-primary">#{inv.number}</td><td className="p-4">{inv.date}<small className="block text-muted">{inv.time}</small></td><td className="p-4">{inv.cashier}</td><td className="p-4">{inv.branch}</td><td className="p-4">{inv.items}</td><td className="p-4"><StatusBadge label={t("completed")}/></td><td className="p-4 text-end font-bold">₪ {inv.total.toFixed(2)}</td><td className="p-4"><Link href={`/invoice/${inv.number}`} className="size-9 rounded-lg bg-primary-soft text-primary grid place-items-center"><Eye size={17}/></Link></td></tr>)}</tbody></table></div></div><Pagination/></AppShell>}

