"use client";
import { useMemo, useState } from "react";
import { CalendarDays, CirclePercent, Edit3, MoreHorizontal, Plus, Store, Trash2, UserRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageToolbar, Pagination, StatusBadge } from "@/components/ui";
import { useLanguage } from "@/components/language-provider";
import { products as seedProducts } from "@/lib/demo-data";

type Kind="products"|"categories"|"discounts"|"employees";
const categories=[{name:"Burgers",ar:"برغر",products:8,order:1,active:true},{name:"Pizza",ar:"بيتزا",products:6,order:2,active:true},{name:"Bowls",ar:"أطباق",products:5,order:3,active:true},{name:"Sides",ar:"إضافات",products:7,order:4,active:true},{name:"Drinks",ar:"مشروبات",products:12,order:5,active:true},{name:"Desserts",ar:"حلويات",products:4,order:6,active:false}];
const campaigns=[{name:"Lunch Hour",ar:"ساعة الغداء",type:"Percentage",value:"15%",scope:"Burgers + Bowls",period:"Jul 1 – Jul 31",active:true},{name:"Coffee Pair",ar:"عرض القهوة",type:"Fixed",value:"₪ 1.50",scope:"Drinks",period:"Jul 3 – Aug 3",active:true},{name:"Weekend Pizza",ar:"بيتزا نهاية الأسبوع",type:"Percentage",value:"10%",scope:"Pizza",period:"Jun 1 – Jun 30",active:false}];
const employees=[{name:"Omar Khalil",email:"omar@noura.test",shift:"Morning",branch:"Main Branch",sales:"₪ 482.50",active:true,initials:"OK"},{name:"Lina Saad",email:"lina@noura.test",shift:"Evening",branch:"Main Branch",sales:"₪ 391.25",active:true,initials:"LS"},{name:"Yousef Ali",email:"yousef@noura.test",shift:"Morning",branch:"Garden Branch",sales:"₪ 276.00",active:true,initials:"YA"},{name:"Rana Odeh",email:"rana@noura.test",shift:"Evening",branch:"Main Branch",sales:"₪ 0.00",active:false,initials:"RO"}];

export default function ManagementPage({kind}:{kind:Kind}){const {t,locale}=useLanguage();const [search,setSearch]=useState("");const [modal,setModal]=useState(false);const [products,setProducts]=useState(seedProducts);const titles={products:t("products"),categories:t("categories"),discounts:t("discounts"),employees:t("employees")};const addLabels={products:t("addProduct"),categories:t("addCategory"),discounts:t("addDiscount"),employees:t("addEmployee")};const filtered=useMemo(()=>products.filter(p=>(p.nameEn+p.nameAr).toLowerCase().includes(search.toLowerCase())),[products,search]);
  const action=<button onClick={()=>setModal(true)} className="btn-primary flex items-center gap-2"><Plus size={17}/><span className="hidden sm:inline">{addLabels[kind]}</span></button>;
  return <AppShell title={titles[kind]} description={`Manage your ${kind} across all branches`} action={action}><PageToolbar search={search} setSearch={setSearch}><select className="input !w-auto"><option>{t("allBranches")}</option><option>Main Branch</option><option>Garden Branch</option></select></PageToolbar>
    <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm min-w-[720px]"><thead className="bg-background text-muted text-xs uppercase tracking-wide"><tr>{kind==="products"&&<><th className="p-4 text-start">{t("products")}</th><th className="p-4 text-start">SKU</th><th className="p-4 text-start">{t("category")}</th><th className="p-4 text-start">{t("price")}</th></>}{kind==="categories"&&<><th className="p-4 text-start">{t("category")}</th><th className="p-4 text-start">{t("products")}</th><th className="p-4 text-start">Sort order</th></>}{kind==="discounts"&&<><th className="p-4 text-start">Campaign</th><th className="p-4 text-start">Type / Value</th><th className="p-4 text-start">Applies to</th><th className="p-4 text-start">Period</th></>}{kind==="employees"&&<><th className="p-4 text-start">{t("employee")}</th><th className="p-4 text-start">Shift</th><th className="p-4 text-start">{t("branch")}</th><th className="p-4 text-start">Today</th></>}<th className="p-4 text-start">{t("status")}</th><th className="p-4 text-end">{t("actions")}</th></tr></thead><tbody>
      {kind==="products"&&filtered.map(p=><tr key={p.id} className="border-t border-border hover:bg-background/60"><td className="p-4"><div className="flex items-center gap-3"><div className="size-12 rounded-xl bg-background grid place-items-center text-2xl">{p.emoji}</div><div><b>{locale==="ar"?p.nameAr:p.nameEn}</b><small className="block text-muted max-w-48 truncate">{locale==="ar"?p.descriptionAr:p.descriptionEn}</small></div></div></td><td className="p-4 text-muted">{`PRD-00${p.id.slice(1)}`}</td><td className="p-4">{locale==="ar"?p.categoryAr:p.category}</td><td className="p-4 font-bold">₪ {p.price.toFixed(2)}</td><td className="p-4"><button onClick={()=>setProducts(old=>old.map(x=>x.id===p.id?{...x,active:!x.active}:x))}><StatusBadge active={p.active}/></button></td><Actions/></tr>)}
      {kind==="categories"&&categories.filter(x=>x.name.toLowerCase().includes(search.toLowerCase())).map(c=><tr key={c.name} className="border-t border-border"><td className="p-4"><b>{locale==="ar"?c.ar:c.name}</b><small className="text-muted block">{c.name} · {c.ar}</small></td><td className="p-4">{c.products} {t("items")}</td><td className="p-4">#{c.order}</td><td className="p-4"><StatusBadge active={c.active}/></td><Actions/></tr>)}
      {kind==="discounts"&&campaigns.filter(x=>x.name.toLowerCase().includes(search.toLowerCase())).map(c=><tr key={c.name} className="border-t border-border"><td className="p-4"><div className="flex gap-3 items-center"><span className="size-10 rounded-xl bg-primary-soft text-primary grid place-items-center"><CirclePercent size={20}/></span><div><b>{locale==="ar"?c.ar:c.name}</b><small className="block text-muted">{c.name} · {c.ar}</small></div></div></td><td className="p-4"><b>{c.value}</b><small className="block text-muted">{c.type}</small></td><td className="p-4">{c.scope}</td><td className="p-4"><span className="flex gap-2 items-center"><CalendarDays size={15} className="text-muted"/>{c.period}</span></td><td className="p-4"><StatusBadge active={c.active}/></td><Actions/></tr>)}
      {kind==="employees"&&employees.filter(x=>x.name.toLowerCase().includes(search.toLowerCase())).map(e=><tr key={e.email} className="border-t border-border"><td className="p-4"><div className="flex gap-3 items-center"><span className="size-10 rounded-full bg-secondary text-white grid place-items-center text-xs font-bold">{e.initials}</span><div><b>{e.name}</b><small className="block text-muted">{e.email}</small></div></div></td><td className="p-4">{e.shift}</td><td className="p-4"><span className="flex gap-2"><Store size={16} className="text-muted"/>{e.branch}</span></td><td className="p-4 font-bold">{e.sales}</td><td className="p-4"><StatusBadge active={e.active}/></td><Actions/></tr>)}
    </tbody></table></div></div><Pagination/>{modal&&<CreateModal kind={kind} close={()=>setModal(false)}/>}</AppShell>}

function Actions(){return <td className="p-4"><div className="flex justify-end gap-1"><button className="size-9 rounded-lg hover:bg-primary-soft text-muted hover:text-primary grid place-items-center"><Edit3 size={16}/></button><button className="size-9 rounded-lg hover:bg-danger/10 text-muted hover:text-danger grid place-items-center"><Trash2 size={16}/></button><button className="size-9 grid place-items-center text-muted"><MoreHorizontal size={18}/></button></div></td>}
function CreateModal({kind,close}:{kind:Kind;close:()=>void}){const {t}=useLanguage();return <div className="fixed inset-0 z-50 bg-text/50 grid place-items-center p-4" onMouseDown={close}><div className="card w-full max-w-lg p-6 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center gap-3"><div className="size-11 rounded-xl bg-primary-soft text-primary grid place-items-center">{kind==="employees"?<UserRound/>:<Plus/>}</div><div><h2 className="font-bold text-xl">{kind==="products"?t("addProduct"):kind==="categories"?t("addCategory"):kind==="discounts"?t("addDiscount"):t("addEmployee")}</h2><p className="text-muted text-sm">English and Arabic details</p></div></div><div className="grid sm:grid-cols-2 gap-4 mt-6"><label><span className="text-xs font-bold block mb-2">Name (English)</span><input className="input" placeholder="Enter name"/></label><label><span className="text-xs font-bold block mb-2">الاسم (العربية)</span><input dir="rtl" className="input" placeholder="أدخل الاسم"/></label><label><span className="text-xs font-bold block mb-2">{kind==="products"?t("price"):kind==="employees"?t("email"):"Reference"}</span><input className="input" placeholder={kind==="products"?"0.00":"Details"}/></label><label><span className="text-xs font-bold block mb-2">{t("branch")}</span><select className="input"><option>Main Branch</option><option>Garden Branch</option></select></label></div><div className="flex justify-end gap-2 mt-7"><button onClick={close} className="btn-secondary">Cancel</button><button onClick={close} className="btn-primary">{t("save")}</button></div></div></div>}

