"use client";
import { Download, TrendingUp } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { useLanguage } from "@/components/language-provider";
import { products, salesDays } from "@/lib/demo-data";

export default function ReportsPage(){const {t,locale}=useLanguage();return <AppShell title={t("reports")} description="Revenue, product, and category performance" action={<button className="btn-secondary flex gap-2 items-center"><Download size={17}/><span className="hidden sm:inline">{t("export")}</span></button>}>
  <div className="card p-4 flex flex-wrap gap-3 mb-5"><select className="input !w-auto"><option>Jul 1 – Jul 6, 2026</option><option>This month</option></select><select className="input !w-auto"><option>{t("allBranches")}</option><option>Main Branch</option></select><select className="input !w-auto"><option>{t("allCategories")}</option></select><button className="btn-primary">{t("filter")}</button></div>
  <div className="grid sm:grid-cols-3 gap-4"><Metric label={t("grossSales")} value="₪ 8,642.25" change="+8.1%"/><Metric label={t("totalInvoices")} value="284" change="+11.2%"/><Metric label="Average order" value="₪ 30.43" change="+2.7%"/></div>
  <div className="grid xl:grid-cols-[1.6fr_1fr] gap-5 mt-5"><div className="card p-5"><h2 className="font-bold">{t("salesOverview")}</h2><p className="text-muted text-xs mt-1">Income by day · ₪</p><div className="h-72 mt-8 flex items-end gap-3 border-b border-border">{salesDays.slice(0,7).map((v,i)=><div key={i} className="flex-1 flex flex-col items-center justify-end h-full gap-2"><span className="text-[10px] text-muted">{v*10}</span><div className="w-full max-w-12 bg-primary rounded-t-lg" style={{height:`${v/1.45}%`}}/><small className="text-muted text-xs">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][i]}</small></div>)}</div></div>
    <div className="card p-5"><h2 className="font-bold">{t("salesCategory")}</h2><div className="mt-7 flex justify-center"><div className="size-44 rounded-full grid place-items-center" style={{background:"conic-gradient(var(--primary) 0 38%, var(--secondary) 38% 65%, var(--warning) 65% 83%, var(--success) 83% 100%)"}}><div className="size-28 rounded-full bg-surface grid place-items-center text-center"><div><b className="text-xl">₪ 8.6k</b><small className="block text-muted">Total</small></div></div></div></div><div className="grid grid-cols-2 gap-3 mt-7">{[["Burgers","38%","bg-primary"],["Pizza","27%","bg-secondary"],["Drinks","18%","bg-warning"],["Other","17%","bg-success"]].map(x=><div key={x[0]} className="flex gap-2 text-sm items-center"><span className={`size-2 rounded-full ${x[2]}`}/><span className="text-muted">{x[0]}</span><b className="ms-auto">{x[1]}</b></div>)}</div></div></div>
  <div className="card mt-5 overflow-hidden"><div className="p-5"><h2 className="font-bold">{t("productPerformance")}</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-background text-muted"><tr><th className="p-4 text-start">{t("products")}</th><th className="p-4 text-start">Units sold</th><th className="p-4 text-start">Revenue</th><th className="p-4 text-start">Share</th></tr></thead><tbody>{products.slice(0,6).map((p,i)=><tr key={p.id} className="border-t border-border"><td className="p-4"><span className="me-3 text-xl">{p.emoji}</span><b>{locale==="ar"?p.nameAr:p.nameEn}</b></td><td className="p-4">{84-i*8}</td><td className="p-4 font-bold">₪ {(714-i*64).toFixed(2)}</td><td className="p-4"><div className="w-28 h-2 rounded-full bg-background"><div className="h-full rounded-full bg-primary" style={{width:`${86-i*10}%`}}/></div></td></tr>)}</tbody></table></div></div>
  </AppShell>}
function Metric({label,value,change}:{label:string;value:string;change:string}){return <div className="card p-5"><p className="text-sm text-muted">{label}</p><div className="flex items-end gap-3 mt-2"><b className="text-2xl">{value}</b><span className="text-xs text-success font-bold flex gap-1"><TrendingUp size={14}/>{change}</span></div></div>}

